<#
.SYNOPSIS
    Helper: Creates a SQL Agent CmdExec job step with PowerShell wrapper script.
.DESCRIPTION
    Generates a wrapper PowerShell script and creates a CmdExec (not PowerShell)
    job step that calls it. This avoids the need for PowerShell Proxy + Credential.

    The wrapper script is generated in:
    C:\Program Files\WindowsPowerShell\Modules\sqmSQLTool\jobs\<FunctionName>-<JobName>.ps1

    The job step simply calls:
    C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy Bypass -File "<wrapper-path>" <params>
.PARAMETER SqlInstance
    SQL Server instance.
.PARAMETER JobName
    Name of the job (for step naming).
.PARAMETER StepName
    Name of the job step. Default: "{FunctionName}_Step1"
.PARAMETER FunctionName
    The sqmSQLTool function to call in the wrapper (e.g. Compare-sqmAlwaysOnLogins).
.PARAMETER Parameters
    Hash of parameters to pass to the function. Converted to script arguments.
.PARAMETER Description
    Optional description for the job step.
.EXAMPLE
    $params = @{
        SqlInstance = 'SQL01'
        AvailabilityGroupName = 'AG_Prod'
        NoOpen = $true
        OutputPath = 'C:\System\WinSrvLog\MSSQL'
    }
    _CreateCmdExecJobStep -SqlInstance 'SQL01' -JobName 'sqmLoginCompare' `
        -FunctionName 'Compare-sqmAlwaysOnLogins' -Parameters $params
#>
function _CreateCmdExecJobStep
{
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$SqlInstance,

        [Parameter(Mandatory = $true)]
        [string]$JobName,

        [Parameter(Mandatory = $false)]
        [string]$StepName = "AutoStep_1",

        [Parameter(Mandatory = $true)]
        [string]$FunctionName,

        [Parameter(Mandatory = $false)]
        [hashtable]$Parameters = @{}
    )

    # -----------------------------------------------------------------------
    # 1. Wrapper-Script Path
    # -----------------------------------------------------------------------
    $modulePath = 'C:\Program Files\WindowsPowerShell\Modules\sqmSQLTool'
    $jobsDir = Join-Path $modulePath 'jobs'

    if (-not (Test-Path $jobsDir)) {
        New-Item -ItemType Directory -Path $jobsDir -Force | Out-Null
    }

    $wrapperName = "$FunctionName-$JobName.ps1"
    $wrapperPath = Join-Path $jobsDir $wrapperName

    # -----------------------------------------------------------------------
    # 2. Build wrapper script content
    # -----------------------------------------------------------------------
    # Convert hashtable parameters to script arguments
    $paramStrings = @()
    foreach ($key in $Parameters.Keys) {
        $value = $Parameters[$key]

        # Handle different types
        if ($value -is [bool]) {
            $paramStrings += "-$key `$$value"
        } elseif ($value -is [int] -or $value -is [double]) {
            $paramStrings += "-$key $value"
        } elseif ($value -is [array]) {
            $arrayStr = ($value | ForEach-Object { "`"$_`"" }) -join ','
            $paramStrings += "-$key @($arrayStr)"
        } else {
            $paramStrings += "-$key `"$value`""
        }
    }

    $paramLine = if ($paramStrings) { " `\`n    " + ($paramStrings -join " `\`n    ") } else { "" }

    $wrapperContent = @"
<#
    Wrapper script for SQL Agent job: $JobName
    Generated by: _CreateCmdExecJobStep
    Function: $FunctionName
    Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
#>

`$ErrorActionPreference = 'Stop'
`$VerbosePreference = 'Continue'

Write-Output "`$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') - Starting $FunctionName"

try {
    Import-Module sqmSQLTool -Force -ErrorAction Stop
    Write-Output "Module loaded."

    $FunctionName$paramLine `
        -Verbose `
        -ContinueOnError

    Write-Output "`$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') - Completed successfully"
    exit 0
} catch {
    Write-Output "ERROR: `$_"
    exit 1
}
"@

    # -----------------------------------------------------------------------
    # 3. Write wrapper script to disk
    # -----------------------------------------------------------------------
    Set-Content -Path $wrapperPath -Value $wrapperContent -Encoding UTF8 -Force
    Write-Verbose "Wrapper script created: $wrapperPath"

    # -----------------------------------------------------------------------
    # 4. Create CmdExec job step
    # -----------------------------------------------------------------------
    $psExePath = 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
    $cmdExecCommand = "$psExePath -NoProfile -ExecutionPolicy Bypass -File `"$wrapperPath`""

    $stepParams = @{
        SqlInstance = $SqlInstance
        Job         = $JobName
        StepName    = $StepName
        Subsystem   = 'CmdExec'
        Command     = $cmdExecCommand
        ErrorAction = 'Stop'
    }

    # Note: dbatools New-DbaAgentJobStep does not support StepDescription parameter.
    # Description is implicit in StepName and visible in SQL Agent UI.

    $jobStep = New-DbaAgentJobStep @stepParams

    Write-Verbose "CmdExec job step created: $StepName"

    # -----------------------------------------------------------------------
    # 5. Return result
    # -----------------------------------------------------------------------
    [PSCustomObject]@{
        SqlInstance    = $SqlInstance
        JobName        = $JobName
        StepName       = $StepName
        FunctionName   = $FunctionName
        WrapperScript  = $wrapperPath
        JobStep        = $jobStep
        Status         = 'Success'
        Timestamp      = Get-Date
    }
}
